---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: app
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/component: api
    environment: production
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 80
      targetPort: http
