---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  sourceRepos:
    - https://charts.jetstack.io
    - https://prometheus-community.github.io/helm-charts
    - https://github.com/boldrqwe/k8s.git
  destinations:
    - namespace: cert-manager
      server: https://kubernetes.default.svc
    - namespace: observability
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
---