envName: prod
fullnameOverride: ""
robots: |
  User-agent: *
  Allow: /
siteTitle: "Demo"
web:
  replicas: 2
  image: nginx:1.25-alpine
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 300m
      memory: 256Mi
api:
  replicas: 1
  image: ealen/echo-server:0.8.10
  port: 8080
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
ingress:
  enabled: true
  host: ""
  tlsSecret: ""
