# environments/production/patches/sc-opensearch.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opensearch
  namespace: data
spec:
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: local-path
