apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-web
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels: { app: prod-web }
  template:
    metadata:
      labels: { app: prod-web }
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
      containers:
        - name: web
          image: ghcr.io/boldrqwe/instructions_front:vX.Y.Z   # не latest!
          env:
            - name: VITE_API_BASE_URL
              value: ""                                      # либо "/"; Ingress отдаёт /api
          ports:
            - name: http
              containerPort: 8080
          securityContext:
            runAsNonRoot: true
            runAsUser: 101
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: cache
              mountPath: /var/cache/nginx
            - name: run
              mountPath: /var/run
      volumes:
        - name: cache
          emptyDir: {}
        - name: run
          emptyDir: {}
