apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-web
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-web
  template:
    metadata:
      labels:
        app: prod-web
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: web
          image: ghcr.io/boldrqwe/instructions_front:latest
          ports:
            - containerPort: 80
          securityContext:
            runAsNonRoot: true
            runAsUser: 101   # nginx в alpine обычно uid 101
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: cache
              mountPath: /var/cache/nginx
            - name: run
              mountPath: /var/run
          volumes:
            - name: cache
              emptyDir: { }
            - name: run
              emptyDir: { }