apiVersion: v1
kind: Service
metadata:
  name: test-api
  namespace: test
spec:
  selector:
    app: test-api
  ports:
    - protocol: TCP
      port: 80        # <-- сервисный порт (то, что видит Ingress)
      targetPort: 8080 # <-- реальный порт контейнера Spring Boot
