apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-prod
  namespace: argocd
spec:
  project: app-project
  source:
    repoURL: oci://registry-1.docker.io/bitnamicharts
    chart: postgresql
    targetRevision: "16.7.27"
    helm:
      values: |
        fullnameOverride: postgres
        auth:
          existingSecret: db-auth
          username: app
          database: app
        primary:
          persistence:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: db
  syncPolicy:
    automated: { selfHeal: true, prune: true }
    syncOptions: [ "CreateNamespace=true" ]
