apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: app
  labels:
    app.kubernetes.io/name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: demo
    spec:
      containers:
        - name: demo
          image: ghcr.io/stefanprodan/podinfo:6.6.2
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: demo-config
          ports:
            - containerPort: 9898
              name: http
