---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: app
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/component: web
    environment: production
