---
apiVersion: v1
kind: Namespace
metadata:
  name: app
  labels:
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/name: app
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
