---
apiVersion: v1
kind: Namespace
metadata:
  name: data
  labels:
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/name: data
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
