---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: streaming-quota
  namespace: streaming
spec:
  hard:
    requests.cpu: "12"
    requests.memory: "32Gi"
    limits.cpu: "24"
    limits.memory: "64Gi"
    persistentvolumeclaims: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: streaming-default-limits
  namespace: streaming
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: "500m"
        memory: "512Mi"
      default:
        cpu: "2"
        memory: "2Gi"
      max:
        cpu: "4"
        memory: "8Gi"
      min:
        cpu: "250m"
        memory: "256Mi"
