---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: observability
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: dashboard
type: Opaque
stringData:
  admin-user: "admin"
  admin-password: "changeMe"
  OPENSEARCH_USERNAME: "admin"
  OPENSEARCH_PASSWORD: "changeMe"
