apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-api
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-api
  template:
    metadata:
      labels:
        app: prod-api
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: backend
          image: ghcr.io/boldrqwe/instructions:latest
          ports:
            - containerPort: 8080
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
          env:
            - name: PORT
              value: "8080"

            # --- DATABASE ---
            - name: DB_HOST
              value: postgres-prod-postgresql
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: instructions
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-postgres-prod   # секрет для prod
                  key: postgres-password    # ключ с паролем

            # --- CORS ---
            - name: CORS_ALLOWED_ORIGINS
              value: https://site.79.174.84.176.sslip.io
