apiVersion: v1
kind: Service
metadata:
  name: prod-api
  namespace: prod
spec:
  selector:
    app: prod-api
  ports:
    - protocol: TCP
      port: 80        # <-- сервисный порт (то, что видит Ingress)
      targetPort: 8080 # <-- реальный порт контейнера Spring Boot
