---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: ConfigMap
      name: demo-config
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: demo-config
      data:
        APP_MESSAGE: Hello from Production
        APP_VERSION: "1.1.0"
  - target:
      kind: Deployment
      name: demo-app
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: demo-app
      spec:
        replicas: 2
