apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: app
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/component: api
    environment: production
