apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-app.fullname" . }}-web
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app: {{ include "demo-app.fullname" . }}-web
  template:
    metadata:
      labels:
        app: {{ include "demo-app.fullname" . }}-web
        {{- include "demo-app.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
      containers:
        - name: web
          image: {{ .Values.web.image }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
      volumes:
        - name: html
          configMap:
            name: {{ include "demo-app.fullname" . }}-content
