---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
  labels:
    app.kubernetes.io/name: demo-app
    app.kubernetes.io/part-of: demo-platform
  namespace: demo
data:
  APP_MESSAGE: "Hello from Kustomize"
  APP_VERSION: "1.0.0"
