---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app.kubernetes.io/name: demo-app
    app.kubernetes.io/part-of: demo-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: demo-app
        app.kubernetes.io/part-of: demo-platform
    spec:
      containers:
        - name: demo-app
          image: nginx:1.25.3
          ports:
            - name: http
              containerPort: 80
          env:
            - name: APP_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: APP_MESSAGE
            - name: APP_VERSION
              valueFrom:
                configMapKeyRef:
                  name: demo-config
                  key: APP_VERSION
