apiVersion: v1
kind: Secret
metadata:
  name: grafana-basic-auth
  namespace: observability
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: dashboard
type: Opaque
stringData:
  auth: |
    # Use htpasswd to generate and replace below (username:password)
    admin:$apr1$example$abcdefghijklmnopqrstuv
