---
name: validate

'on':
  pull_request:
  push:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      KUSTOMIZE_DIR: environments/production
    steps:
      - uses: actions/checkout@v4

      - name: Set up kustomize
        uses: imranismail/setup-kustomize@v2
        with:
          kustomize-version: '5.1.0'

      - name: Install kubeconform
        run: |
          curl -sSL https://github.com/yannh/kubeconform/releases/download/v0.6.3/kubeconform-linux-amd64.tar.gz \
            | sudo tar -xz -C /usr/local/bin kubeconform

      - name: Render manifests
        run: kustomize build "$KUSTOMIZE_DIR" > manifest.yaml

      - name: Validate (kubeconform)
        run: kubeconform -strict -ignore-missing-schemas -summary manifest.yaml

      - name: Lint YAML
        uses: ibiqlik/action-yamllint@v3
        with:
          config_data: |
            extends: default
            rules:
              indentation:
                indent-sequences: whatever
              line-length:
                max: 160
                level: warning
